# PostgreSQL. Versions 8.2 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On Mac OS X with macports:
#   gem install pg -- --with-pg-config=/opt/local/lib/postgresql84/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem 'pg'
#
development:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: viewy_development
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASS'] %>
  host: localhost
  port: <%= ENV['APP_PORT'] %>
  schema_search_path: public,foo

test:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: viewy_test
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASS'] %>
  host: localhost
  port: <%= ENV['APP_PORT'] %>
  schema_search_path: public,foo

